tutorial/tutorial_app/urls.py
from django.conf.urls import url

from . import views

app_name = 'tutorial_app'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^success/', views.LoginSuccess.as_view(), name='success'),
    url(r'^register/', views.Register.as_view(), name='register'),
    url(r'^login/', views.login_user, name='login'),
    url(r'^register_user/', views.register_user, name='register_user'),
    url(r'^logout/', views.logout_user, name= 'logout'),
]

tutorial/tutorial_settings/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('tutorial_app.urls'), name='tutorial_app')
]

tutorial/tutorial_app/models.py
from django.db import models

# Create your models here.

tutorial/tutorial_app/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth import logout, login, authenticate
from django.http import HttpResponse, HttpResponseRedirect

# Create your views here.

class IndexView(TemplateView):
    template_name = 'tutorial_app/login.html'


class LoginSuccess(LoginRequiredMixin, TemplateView):
    template_name = 'tutorial_app/home.html'


class Register(TemplateView):
    template_name = 'tutorial_app/register.html'


def register_user(request):
    data = request.POST
    User.objects.create_user(username=data['username'], email=data['email'],
    	first_name=data['first_name'], password=data['password'], last_name=data['last_name'])
    return login_user(request)


def login_user(request):
    data = request.POST
    username= data['username']
    password = data['password']
    user= authenticate(username=username, password=password)

    if user is not None:
    	login(request=request, user=user)
    else:
    	return HttpResponseRedirect(redirect_to='/')
    return HttpResponseRedirect(redirect_to='/success')

def logout_user(request):
	logout(request)
	return HttpResponseRedirect(redirect_to='/')    

tutorial/tutorial_app/templates/tutorial_app/home.html
{% extends 'tutorial_app/index.html' %}

{% block content %}
  <a href="{% url 'tutorial_app:logout' %}">Log Out</a>
  <div id="_giphy_tv"></div>
{% endblock %}

tutorial/tutorial_app/templates/tutorial_app/index.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Django Auth Tutorial</title>
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
  </head>
  <body>
    {% block content %}{% endblock %}
    <script type="text/javascript" src="{% static 'main.js' %}"></script>
  </body>
</html>

tutorial/tutorial_app/templates/tutorial_app/login.html
{% extends 'tutorial_app/index.html' %}

{% block content %}

<form class="" action="{% url 'tutorial_app:login' %}" method="post">
	<input type="text" name="username" value="" placeholder="Enter username">
	{% csrf_token %}
	<input type="text" name="password" value= "" placeholder="Enter password">
</form>
<p>Not a user? Register <a href="{% url 'tutorial_app:register' %}"> here</a></p>
{% endblock %}

tutorial/tutorial_app/templates/tutorial_app/register.html
{% extends 'tutorial_app/index.html' %}

{% block content %}

<form class="" action="{% url 'tutorial_app:register_user' %}" method="post">
	{% csrf_token %}
	<input type="text" name="username" value="" placeholder="username">
	<input type="text" name="email" value="" placeholder="email">
	<input type="text" name="password" value="" placeholder="password">
	<input type="text" name="first_name" value="" placeholder="first_name">
	<input type="text" name="last_name" value="" placeholder="last_name">
<button type="submit" name="button">Submit</button>
</form>

{% endblock %}